#Python basics

In [ ]:
print("Hello world")

Hello world


In [ ]:
print("hello this is ujwala's colab")

hello this is ujwala's colab


In [ ]:
print(2)

2


In [ ]:
print('2')

2


In [ ]:
a=21  #a is 21
b=31  #b is 31

In [ ]:
'''a is 21 b is 31'''
a=21
b=31

In [ ]:
a=21
type(a)

int

In [ ]:
a=21,21
type(a)

tuple

In [ ]:
a=21,
type(a)

tuple

In [ ]:
a=[21,22]
type(a)

list

In [ ]:
a=[1,2,3]
a

[1, 2, 3]

In [ ]:
a[1]

2

In [ ]:
a[1]='ujwala'
a

[1, 'ujwala', 3]

In [ ]:
a[2]=2+2j
a

[1, 'ujwala', (2+2j)]

In [ ]:
type(a)

list

In [ ]:
set_1 = {1,2,5,7,'Hari','Srikanth','Saumya',2+4j}
set_1

{(2+4j), 1, 2, 5, 7, 'Hari', 'Saumya', 'Srikanth'}

In [ ]:

dict_1 = {'S.No':1,
          'Name':'Hari'}

dict_1


{'S.No': 1, 'Name': 'Hari'}

In [ ]:

dict_1['S.No']

1

In [ ]:

dict_1 = {'S.No':1,
          'Name':'Hari',
          'S.Nno':1}

dict_1

{'S.No': 1, 'Name': 'Hari', 'S.Nno': 1}

In [ ]:

# Indexing & Slicing

list1 = [12,11,23,31,'Hari']
list2 = [10,[1,2],3,['Hari','Srikanth','Saumya']]
list1
list2

[10, [1, 2], 3, ['Hari', 'Srikanth', 'Saumya']]

In [ ]:
type(list1),type(list2)

(list, list)

In [ ]:
list1[0]

12

In [ ]:
list1[0:3]

[12, 11, 23]

#Numpy and Pandas

In [5]:
import numpy as np          #numpy only acceptgs numerical values it wont acceptg the string values because it is a numerical python
import pandas as pd
a = np.array([12,34,56,82])
a
print(a[1])   #indexing is possible in arrays
print(a[1:3])  #slicing is also possible in arrays

34
[34 56]


In [11]:

import numpy as np          #numpy only acceptgs numerical values it wont acceptg the string values because it is a numerical python
import pandas as pd
a = np.array([12,34,56,82])
a
a[1]=100
print(a)
print(a.ndim)
type(a)

[ 12 100  56  82]
1


numpy.ndarray

In [20]:
import numpy as np          #numpy only acceptgs numerical values it wont acceptg the string values because it is a numerical python
import pandas as pd
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
print(b[1])
print(b[1][2])
print(b[1][0:2])   #here in multi dimensional array also the indexing and slicing is possible
print(b.min(),b.max())
print(type(b))

[[1 2 3]
 [4 5 6]]
2
[4 5 6]
6
[4 5]
1 6
<class 'numpy.ndarray'>


In [27]:
import numpy as np          #numpy only acceptgs numerical values it wont acceptg the string values because it is a numerical python
import pandas as pd
print(np.arange(10))     #first method in arange
print(np.arange(20,40))   #second method in arange we are giving the starting and ending values
print(np.arange(20,40,4))   #third method in arange here we are giving the starting,ending,and step value also  ,here step value is the difference
print(np.arange(40,20))    #here the empty array is creating
print(np.arange(40,20,-2))  #here we are giving the negative indexing
print(np.linspace(10,100,4))  #here starting value is 10 and ending value is 100 and the step value is the no.of values to be in the range from starting value to ending value

[0 1 2 3 4 5 6 7 8 9]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[20 24 28 32 36]
[]
[40 38 36 34 32 30 28 26 24 22]
[ 10.  40.  70. 100.]


#Pandas

In [29]:
#pandas is divided into two parts (Series,Dataframe)
import numpy as np
import pandas as pd
a=pd.Series(np.arange(9))   #series means single column and dataframe means collection of single columns
print(a)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64


In [30]:
import numpy as np
import pandas as pd
b=pd.Series(np.arange(3))
print(b)

0    0
1    1
2    2
dtype: int64


In [33]:
import numpy as np
import pandas as pd
c=pd.DataFrame([a,b])   #combining the series of a and b
print(c)
print(c.T)  #transpose of a matrix,it converts the rows in to columns and columns in to rows

     0    1    2    3    4    5    6    7    8
0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0
1  0.0  1.0  2.0  NaN  NaN  NaN  NaN  NaN  NaN
     0    1
0  0.0  0.0
1  1.0  1.0
2  2.0  2.0
3  3.0  NaN
4  4.0  NaN
5  5.0  NaN
6  6.0  NaN
7  7.0  NaN
8  8.0  NaN


In [36]:
import numpy as np
import pandas as pd
dummy={'Name':['ujwala','latha','geetha',np.nan],'Age':[15,np.nan,23,45],'Track':['ai',np.nan,'ml',np.nan]}
print(dummy)

{'Name': ['ujwala', 'latha', 'geetha', nan], 'Age': [15, nan, 23, 45], 'Track': ['ai', nan, 'ml', nan]}


In [37]:
a=pd.DataFrame(dummy)
print(a)

     Name   Age Track
0  ujwala  15.0    ai
1   latha   NaN   NaN
2  geetha  23.0    ml
3     NaN  45.0   NaN


In [42]:
a.Name

(0    ujwala
 1     latha
 2    geetha
 3       NaN
 Name: Name, dtype: object,
 0    15.0
 1     NaN
 2    23.0
 3    45.0
 Name: Age, dtype: float64)

In [41]:
a['Name'],a['Age']       #we can use a.Name or a['Name']

(0    ujwala
 1     latha
 2    geetha
 3       NaN
 Name: Name, dtype: object,
 0    15.0
 1     NaN
 2    23.0
 3    45.0
 Name: Age, dtype: float64)

In [43]:
type(a)    #here the type of dataframe is pandas

pandas.core.frame.DataFrame

In [44]:
a.info()    #to know the datatype of a dataframe we are using a.info() and here we have to convert the object into int or float

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    3 non-null      object 
 1   Age     3 non-null      float64
 2   Track   2 non-null      object 
dtypes: float64(1), object(2)
memory usage: 224.0+ bytes


In [46]:
a.isnull()    #to know how many null values are there in the dataframe

Name    Age  Track
0  False  False  False
1  False   True   True
2  False  False  False
3   True  False   True

In [47]:
a.isnull().sum()    #here we can know the sum of the null values in each column

Name     1
Age      1
Track    2
dtype: int64

#location(loc) and indexlocation(iloc)

In [49]:
a.loc[0:2,'Name':'Age']     #here before comma are rows i.e from 0 to 2 and after comma is columns i.e Name and Age

Name   Age
0  ujwala  15.0
1   latha   NaN
2  geetha  23.0

In [51]:
a.iloc[0:3,0:2]      #here we have to specify the index i.e before comma are rows i.e 0 to 3 means 0,1,2 and after comma are columns i.e 0:2 means 0,1 columns we are getting

Name   Age Track
0  ujwala  15.0    ai
1   latha   NaN   NaN
2  geetha  23.0    ml